"""Tests for content_safety guardrail module."""

import pytest
from src.guardrails.content_safety import (
    filter_report_content,
    add_regulatory_footer,
    validate_score_language_consistency,
)


class TestFilterReportContent:
    def test_softens_will_default(self):
        report = "Based on our analysis, the company will default within 6 months."
        cleaned, mods = filter_report_content(report)
        assert "will default" not in cleaned
        assert "elevated default risk" in cleaned
        assert len(mods) == 1

    def test_softens_deny_credit(self):
        report = "We recommend to deny credit to this applicant."
        cleaned, mods = filter_report_content(report)
        assert "deny credit" not in cleaned
        assert "additional review" in cleaned

    def test_softens_cannot_repay(self):
        report = "The borrower cannot repay the outstanding loan."
        cleaned, mods = filter_report_content(report)
        assert "cannot repay" not in cleaned
        assert "challenges" in cleaned

    def test_no_changes_for_safe_report(self):
        report = "The company shows moderate risk with diversified revenue streams."
        cleaned, mods = filter_report_content(report)
        assert cleaned == report
        assert len(mods) == 0

    def test_multiple_rules_applied(self):
        report = "The company will default and should not lend to them."
        cleaned, mods = filter_report_content(report)
        assert "will default" not in cleaned
        assert "should not lend" not in cleaned
        assert len(mods) == 2


class TestAddRegulatoryFooter:
    def test_footer_added(self):
        report = "Company analysis complete."
        result = add_regulatory_footer(report)
        assert "Disclaimer" in result
        assert "does not constitute financial advice" in result

    def test_footer_not_duplicated(self):
        report = "Analysis. This report is generated by an AI system for info."
        result = add_regulatory_footer(report)
        assert result == report  # Should not add again


class TestValidateScoreLanguageConsistency:
    def test_consistent_low_risk(self):
        score = {"rating": "Low", "score": 20}
        report = (
            "The company shows strong growth, robust margins, healthy cash flow, "
            "solid fundamentals, and positive outlook for the sector."
        )
        warnings = validate_score_language_consistency(score, report)
        assert len(warnings) == 0

    def test_inconsistent_low_risk_many_negatives(self):
        score = {"rating": "Low", "score": 15}
        report = (
            "Significant risk of decline with debt default concern and loss. "
            "Further weakness and deterioration expected. Volatile and unstable outlook. "
            "Critical warning signs observed."
        )
        warnings = validate_score_language_consistency(score, report)
        assert len(warnings) > 0
        assert "inconsistency" in warnings[0].lower()

    def test_inconsistent_high_risk_many_positives(self):
        score = {"rating": "High", "score": 85}
        report = (
            "Strong growth and profit with stable and positive performance. "
            "Robust and healthy operations showing improvement. "
            "Solid fundamentals with excellent efficiency and leading position."
        )
        warnings = validate_score_language_consistency(score, report)
        assert len(warnings) > 0

    def test_no_rating_warns(self):
        score = {"score": 50}
        report = "Some report text."
        warnings = validate_score_language_consistency(score, report)
        assert any("no rating" in w.lower() for w in warnings)
