"""Bias and fairness guardrails for credit risk assessment.

Detects protected class proxy variables, filters biased content, and
checks compliance with MAS FEAT principles and EU AI Act requirements.
All checks are pure regex/string-based with zero LLM tokens.
"""

import re
from typing import Tuple


# --- Protected class terms organized by category and severity ---
PROTECTED_TERMS = {
    "demographics": {
        "severity": "high",
        "terms": [
            "race", "racial", "ethnicity", "ethnic", "african american",
            "caucasian", "hispanic", "latino", "latina", "asian",
            "white", "black", "indigenous", "native american",
            "gender", "male", "female", "non-binary", "transgender",
            "religion", "religious", "christian", "muslim", "jewish",
            "hindu", "buddhist", "sikh", "atheist",
            "nationality", "national origin", "immigrant", "citizen",
            "foreigner", "alien", "refugee",
        ],
    },
    "geographic_proxy": {
        "severity": "medium",
        "terms": [
            "zip code", "zipcode", "zip-code", "postal code",
            "neighborhood", "neighbourhood", "district", "borough",
            "inner city", "inner-city", "suburb", "rural area",
            "urban area", "ghetto", "barrio",
        ],
    },
    "personal": {
        "severity": "low",
        "terms": [
            "age", "elderly", "senior citizen", "young adult",
            "marital status", "married", "divorced", "single parent",
            "widowed", "separated", "family status", "pregnant",
            "disability", "disabled", "handicapped",
            "sexual orientation", "gay", "lesbian", "bisexual",
        ],
    },
}


def _build_term_index():
    """Build a flat lookup from term to (category, severity)."""
    index = {}
    for category, info in PROTECTED_TERMS.items():
        for term in info["terms"]:
            index[term.lower()] = (category, info["severity"])
    return index


_TERM_INDEX = _build_term_index()


def detect_proxy_variables(text: str) -> list:
    """Scan text for protected class terms and proxy variables.

    Returns a list of dicts with keys: term, category, severity.
    """
    text_lower = text.lower()
    found = []
    seen = set()
    for term, (category, severity) in _TERM_INDEX.items():
        if term in seen:
            continue
        # Use word boundary matching to avoid false positives
        pattern = r'\b' + re.escape(term) + r'\b'
        if re.search(pattern, text_lower):
            found.append({
                "term": term,
                "category": category,
                "severity": severity,
            })
            seen.add(term)
    return found


def _contains_protected_terms(text: str) -> bool:
    """Return True if text contains any protected class term."""
    text_lower = text.lower()
    for term in _TERM_INDEX:
        pattern = r'\b' + re.escape(term) + r'\b'
        if re.search(pattern, text_lower):
            return True
    return False


def filter_protected_class_references(
    risks: list, strengths: list
) -> Tuple[list, list, list]:
    """Remove risk/strength items that reference protected classes.

    Returns (cleaned_risks, cleaned_strengths, removed_log).
    """
    cleaned_risks = []
    cleaned_strengths = []
    removed_log = []

    for i, risk in enumerate(risks):
        desc = risk.get("description", "") if isinstance(risk, dict) else str(risk)
        if _contains_protected_terms(desc):
            removed_log.append(
                f"Risk at index {i} removed: references protected class terms."
            )
        else:
            cleaned_risks.append(risk)

    for i, strength in enumerate(strengths):
        desc = strength.get("description", "") if isinstance(strength, dict) else str(strength)
        if _contains_protected_terms(desc):
            removed_log.append(
                f"Strength at index {i} removed: references protected class terms."
            )
        else:
            cleaned_strengths.append(strength)

    return cleaned_risks, cleaned_strengths, removed_log


def generate_fairness_disclaimer() -> str:
    """Return a MAS FEAT / EU AI Act compliant fairness disclaimer."""
    return (
        "This credit risk assessment has been generated by an AI system designed "
        "to comply with the Monetary Authority of Singapore (MAS) Fairness, Ethics, "
        "Accountability and Transparency (FEAT) principles and the European Union "
        "Artificial Intelligence Act (EU AI Act). The assessment does not use protected "
        "class attributes including race, ethnicity, gender, religion, nationality, "
        "age, marital status, disability, or sexual orientation as factors in the "
        "credit risk evaluation. All risk signals are derived from publicly available "
        "financial data, market indicators, and business performance metrics. This "
        "output is intended for use by qualified credit analysts and does not "
        "constitute an automated credit decision."
    )


def check_mas_feat_compliance(report: str) -> dict:
    """Check report against MAS FEAT principles.

    Checks:
    - Fairness: no bias/protected class terms in report
    - Ethics: data provenance is cited
    - Accountability: human oversight note present
    - Transparency: methodology is stated

    Returns {principle: bool}.
    """
    report_lower = report.lower()

    # Fairness: no protected class terms with high severity
    high_severity_found = False
    for term, (_, severity) in _TERM_INDEX.items():
        if severity == "high":
            pattern = r'\b' + re.escape(term) + r'\b'
            if re.search(pattern, report_lower):
                high_severity_found = True
                break
    fairness = not high_severity_found

    # Ethics: data provenance cited
    provenance_patterns = [
        r'data\s+source', r'sourced\s+from', r'based\s+on\s+data',
        r'data\s+provenance', r'obtained\s+from', r'collected\s+from',
        r'publicly\s+available', r'financial\s+filing', r'sec\s+filing',
        r'annual\s+report',
    ]
    ethics = any(re.search(p, report_lower) for p in provenance_patterns)

    # Accountability: human oversight note
    accountability_patterns = [
        r'human\s+oversight', r'human\s+review', r'reviewed\s+by',
        r'credit\s+analyst', r'human\s+judgment', r'manual\s+review',
        r'qualified\s+analyst', r'human\s+in\s+the\s+loop',
    ]
    accountability = any(
        re.search(p, report_lower) for p in accountability_patterns
    )

    # Transparency: methodology stated
    transparency_patterns = [
        r'methodolog', r'approach\s+used', r'assessment\s+framework',
        r'scoring\s+model', r'risk\s+model', r'analysis\s+method',
        r'evaluation\s+criteria', r'ai\s+system', r'machine\s+learning',
        r'natural\s+language\s+processing',
    ]
    transparency = any(
        re.search(p, report_lower) for p in transparency_patterns
    )

    return {
        "fairness": fairness,
        "ethics": ethics,
        "accountability": accountability,
        "transparency": transparency,
    }


def check_eu_ai_act_compliance(report: str) -> dict:
    """Check report against EU AI Act requirements for high-risk AI systems.

    Checks for human oversight note, data provenance, transparency
    statement, and absence of protected class terms.

    Returns checklist dict with bool values.
    """
    report_lower = report.lower()

    # Human oversight note
    oversight_patterns = [
        r'human\s+oversight', r'human\s+review', r'reviewed\s+by',
        r'human\s+in\s+the\s+loop', r'manual\s+review',
        r'qualified\s+(credit\s+)?analyst',
    ]
    human_oversight = any(
        re.search(p, report_lower) for p in oversight_patterns
    )

    # Data provenance
    provenance_patterns = [
        r'data\s+source', r'sourced\s+from', r'data\s+provenance',
        r'obtained\s+from', r'publicly\s+available', r'financial\s+filing',
    ]
    data_provenance = any(
        re.search(p, report_lower) for p in provenance_patterns
    )

    # Transparency statement
    transparency_patterns = [
        r'ai\s+system', r'ai\s+generated', r'ai-generated',
        r'automated\s+system', r'machine\s+learning',
        r'artificial\s+intelligence', r'algorithmic',
    ]
    transparency_statement = any(
        re.search(p, report_lower) for p in transparency_patterns
    )

    # No protected class terms
    no_protected_terms = not _contains_protected_terms(report)

    return {
        "human_oversight": human_oversight,
        "data_provenance": data_provenance,
        "transparency_statement": transparency_statement,
        "no_protected_terms": no_protected_terms,
    }
