"""Content safety guardrails for credit risk reports.

Softens definitive credit language, appends regulatory disclaimers,
and checks score-language consistency. All checks are regex-based.
"""

import re
from typing import Tuple


# --- Definitive language replacement rules ---
# Each tuple: (pattern, replacement, description)
SOFTENING_RULES = [
    (
        r'\bshould\s+not\s+lend\b',
        'elevated risk profile warrants further review',
        'Softened definitive lending denial',
    ),
    (
        r'\bwill\s+default\b',
        'shows indicators of elevated default risk',
        'Softened definitive default prediction',
    ),
    (
        r'\bdeny\s+credit\b',
        'warrants additional review before credit extension',
        'Softened definitive credit denial',
    ),
    (
        r'\bmust\s+not\s+lend\b',
        'elevated risk profile warrants further review',
        'Softened mandatory lending denial',
    ),
    (
        r'\breject\s+(the\s+)?application\b',
        'warrants additional review before credit extension',
        'Softened application rejection',
    ),
    (
        r'\bwill\s+certainly\s+fail\b',
        'shows indicators of elevated risk',
        'Softened certainty language',
    ),
    (
        r'\bguaranteed\s+to\s+default\b',
        'shows indicators of elevated default risk',
        'Softened guaranteed default language',
    ),
    (
        r'\bcannot\s+repay\b',
        'may face challenges in meeting repayment obligations',
        'Softened repayment certainty',
    ),
    (
        r'\bwill\s+go\s+bankrupt\b',
        'shows indicators of elevated financial distress',
        'Softened bankruptcy prediction',
    ),
    (
        r'\bdo\s+not\s+approve\b',
        'warrants additional review before approval',
        'Softened approval denial',
    ),
]

REGULATORY_FOOTER = (
    "\n\n---\n**Disclaimer**: This report is generated by an AI system for "
    "informational purposes only. It does not constitute financial advice "
    "or a credit decision. All outputs should be reviewed by a qualified "
    "credit analyst in accordance with applicable MAS guidelines and "
    "internal risk policies."
)

# --- Word lists for score-language consistency ---
NEGATIVE_WORDS = {
    "risk", "decline", "loss", "debt", "default", "downgrade", "negative",
    "concern", "weakness", "threat", "deteriorat", "poor", "adverse",
    "volatile", "unstable", "danger", "warning", "critical", "severe",
    "problematic", "troubled", "distress", "delinquent", "impair",
    "worsen", "fail", "falling", "drop", "shrink", "deficit",
}

POSITIVE_WORDS = {
    "strong", "growth", "profit", "stable", "positive", "improve",
    "robust", "healthy", "solid", "excellent", "outperform", "gain",
    "increase", "upward", "favorable", "resilient", "advantage",
    "opportunity", "strength", "success", "reliable", "consistent",
    "efficient", "leading", "innovative", "growing", "expanding",
}


def filter_report_content(report: str) -> Tuple[str, list]:
    """Soften definitive credit recommendations in the report.

    Replaces harsh/definitive language with cautious alternatives.
    Returns (cleaned_report, modifications_log).
    """
    modifications_log = []
    cleaned = report

    for pattern, replacement, description in SOFTENING_RULES:
        matches = re.findall(pattern, cleaned, flags=re.IGNORECASE)
        if matches:
            cleaned = re.sub(pattern, replacement, cleaned, flags=re.IGNORECASE)
            modifications_log.append(
                f"{description}: {len(matches)} occurrence(s) replaced."
            )

    return cleaned, modifications_log


def add_regulatory_footer(report: str) -> str:
    """Append regulatory disclaimer footer to the report."""
    # Avoid appending if already present
    if "This report is generated by an AI system" in report:
        return report
    return report + REGULATORY_FOOTER


def _count_word_matches(text: str, word_set: set) -> int:
    """Count how many words from word_set appear in text."""
    text_lower = text.lower()
    count = 0
    for word in word_set:
        if word in text_lower:
            count += 1
    return count


def validate_score_language_consistency(
    score: dict, report: str
) -> list:
    """Check consistency between the risk score rating and report language.

    If rating is 'Low' but report has many negative words, or 'High' but
    many positive words, flag the inconsistency.

    Returns a list of warning strings.
    """
    warnings = []
    rating = score.get("rating", "")
    if not rating:
        warnings.append("No rating found in score dict.")
        return warnings

    neg_count = _count_word_matches(report, NEGATIVE_WORDS)
    pos_count = _count_word_matches(report, POSITIVE_WORDS)

    # Thresholds: if dominant sentiment contradicts rating
    if rating == "Low" and neg_count > pos_count and neg_count >= 5:
        warnings.append(
            f"Rating is 'Low' (low risk) but report contains {neg_count} "
            f"negative terms vs {pos_count} positive terms. "
            "Possible score-language inconsistency."
        )
    elif rating == "High" and pos_count > neg_count and pos_count >= 5:
        warnings.append(
            f"Rating is 'High' (high risk) but report contains {pos_count} "
            f"positive terms vs {neg_count} negative terms. "
            "Possible score-language inconsistency."
        )

    return warnings
